name: Test silent-mouse script across ubuntu distros

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #distro-versions: ['debian:10', 'debian:11', 'debian:12']
        #distro-versions: ['ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:22.04', 'debian:10', 'debian:11', 'debian:12', 'manjarolinux/base:latest']
        #distro-versions: ['ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:22.04']
        distro-versions: ['ubuntu:22.04']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t test-env --build-arg DISTRO_VERSION=${{ matrix.distro-versions }} .

    - name: Run Script in Docker Container
      run: |
        docker run -t --privileged test-env /bin/bash -c "git clone https://github.com/guiambros/silent-mouse; cd silent-mouse; bash silent-mouse.sh"
