name: 'Test on various Linux distros'

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  linux-distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro-versions: ['ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:22.04', 'debian:10', 'debian:11', 'debian:12', 'manjarolinux/base:latest']
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Check package system installed
      run: |
        if [[ ${{ matrix.distro-versions }} == *manjaro* ]]; then \
          ln -s Dockerfile-pacman Dockerfile; else \
          ln -s Dockerfile-debian Dockerfile; fi
    - name: Build docker environment
      run: |
        docker build -t test_env --build-arg DISTRO_VERSION=${{ matrix.distro-versions }} .
    - name: Test script on ${{ matrix.distro-versions }}
      run: |
        docker run -t --privileged test_env /bin/bash -c "cd /repo; git checkout dev; bash silent-mouse.sh; exit"